(function(root){
'use strict';
const finite=(x)=>{if(typeof x!=='number'||!Number.isFinite(x))throw Error('请输入有限数值');return x;};
const mean=a=>a.reduce((s,x)=>s+x,0)/a.length;
const cov=(a,b)=>{if(a.length<2||a.length!==b.length)throw Error('共同样本不足');let x=mean(a),y=mean(b);return a.reduce((s,v,i)=>s+(v-x)*(b[i]-y),0)/(a.length-1);};
const sd=a=>Math.sqrt(Math.max(0,cov(a,a)));
const ratio=(a,b)=>b>0?a/b:null;
function date(x){if(typeof x!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(x)||!Number.isFinite(Date.parse(x+'T00:00:00Z'))||new Date(x+'T00:00:00Z').toISOString().slice(0,10)!==x)throw Error('日期无效');return x;}
function historical(d){
 date(d.asOf);const periods={daily:252,monthly:12}[d.frequency];if(!periods)throw Error('须明确日频或月频');
 const rf=finite(d.riskFreeAnnualPct)/100;if(rf<=-1)throw Error('无风险年率无效');
 const rows=d.assets;if(!Array.isArray(rows)||!rows.length||new Set(rows.map(x=>x.code)).size!==rows.length)throw Error('资产代码须非空且唯一');
 const first=rows[0].history;if(!Array.isArray(first)||first.length<4)throw Error('至少需要四期完整观察');
 const dates=first.map(x=>date(x.date));if(new Set(dates).size!==dates.length||dates.some((x,i)=>x>d.asOf||(i&&x<=dates[i-1])))throw Error('日期重复、乱序或超过截止日');
 if(d.frequency==='monthly'&&dates.some((x,i)=>i&&(Number(x.slice(0,4))*12+Number(x.slice(5,7)))-(Number(dates[i-1].slice(0,4))*12+Number(dates[i-1].slice(5,7)))!==1))throw Error('月频必须逐月连续');
 if(d.frequency==='daily'){
  const gaps=dates.slice(1).map((x,i)=>(Date.parse(x)-Date.parse(dates[i]))/86400000),sorted=[...gaps].sort((a,b)=>a-b),mid=Math.floor(sorted.length/2),median=sorted.length%2?sorted[mid]:(sorted[mid-1]+sorted[mid])/2;
  if(median>3||Math.max(...gaps)>14)throw Error('日频间隔不满足年化要求；不能将稀疏或长期缺失观察按252期年化');
 }
 const weights=rows.map(x=>finite(x.weight));if(weights.some(x=>x<0)||Math.abs(weights.reduce((s,x)=>s+x,0)-1)>1e-8)throw Error('权重必须非负且合计100%');
 const ret=rows.map(x=>{if(!x.code||!x.sourceUrl||x.currency!==d.currency||x.basis!=='total-return'||!Array.isArray(x.history)||x.history.length!==dates.length)throw Error('需要来源、同币种和总收益口径共同历史');let v=x.history.map((o,i)=>{if(date(o.date)!==dates[i])throw Error('资产日期必须完全一致，不自动填充');let z=finite(o.value);if(z<=0)throw Error('总收益指数须为正');return z;});return v.slice(1).map((z,i)=>z/v[i]-1);});
 const rfPeriod=Math.pow(1+rf,1/periods)-1;
 function metrics(a){let end=1,peak=1,dd=0;a.forEach(x=>{end*=1+x;peak=Math.max(peak,end);dd=Math.max(dd,1-end/peak);});let years=(Date.parse(dates.at(-1))-Date.parse(dates[0]))/86400000/365.25;let cagr=Math.pow(end,1/years)-1;let volatility=sd(a)*Math.sqrt(periods);let excess=a.map(x=>x-rfPeriod);let down=Math.sqrt(mean(excess.map(x=>Math.min(0,x)**2)))*Math.sqrt(periods);let positive=a.filter(x=>x>0),negative=a.filter(x=>x<0);let upper=Math.sqrt(mean(a.map(x=>Math.max(0,x)**2)))*Math.sqrt(periods),lower=Math.sqrt(mean(a.map(x=>Math.min(0,x)**2)))*Math.sqrt(periods);let losses=a.map(x=>-x).sort((x,y)=>x-y);
 const tails=[.95,.99].map(conf=>{let mass=(1-conf)*losses.length,whole=Math.floor(mass),part=mass-whole;let sum=0;for(let i=0;i<whole;i++)sum+=losses[losses.length-1-i];if(part>1e-12)sum+=part*losses[losses.length-1-whole];return {confidence:conf,VaRPct:losses[Math.max(0,Math.ceil(conf*losses.length)-1)]*100,CVaRPct:sum/mass*100,tailObservations:mass};});
 return {CAGRPct:cagr*100,annualVolatilityPct:volatility*100,maximumDrawdownPct:dd*100,upsideDeviationPct:upper*100,downsideDeviationPct:lower*100,sortinoTargetDownsideDeviationPct:down*100,positiveReturnCount:positive.length,negativeReturnCount:negative.length,conditionalPositiveVolatilityPct:positive.length>=2?sd(positive)*Math.sqrt(periods)*100:null,conditionalNegativeVolatilityPct:negative.length>=2?sd(negative)*Math.sqrt(periods)*100:null,Sharpe:ratio(mean(excess)*periods,volatility),Sortino:ratio(mean(excess)*periods,down),Calmar:ratio(cagr,dd),historicalTail:tails};}
 const covariance=ret.map(a=>ret.map(b=>cov(a,b)*periods));const correlations=ret.map(a=>ret.map(b=>ratio(cov(a,b),sd(a)*sd(b))));
 const portfolio=ret[0].map((_,i)=>ret.reduce((s,a,j)=>s+a[i]*weights[j],0));
 let variance=weights.reduce((s,w,i)=>s+w*weights.reduce((t,v,j)=>t+v*covariance[i][j],0),0);
 return {type:'historical',asOf:d.asOf,start:dates[0],end:dates.at(-1),observations:portfolio.length,codes:rows.map(x=>x.code),assets:rows.map((x,i)=>({code:x.code,...metrics(ret[i])})),correlations,annualCovariance:covariance,portfolio:{...metrics(portfolio),sampleArithmeticAnnualReturnPct:mean(portfolio)*periods*100,annualVariance:variance},limitations:['上行/下行偏差以0为阈值、全部观察数为分母；正/负收益条件标准差另列，子样本不足两期为null。索提诺使用无风险年率折算的每期目标，分母为目标下行偏差；零分母不输出无限大。','历史样本，不是预期收益预测；VaR为损失分位数，不是最大亏损。','组合序列假设每个观察期无成本恢复目标权重，不等于买入持有或真实再平衡回测。','夏普使用算术超额收益；CAGR使用实际日历年。日频由输入声明，未核验交易日历。','尾部样本量小；历史CVaR按最差尾部概率质量加权，不使用正态假设；未见尾部不能证明安全。']};
}
function shock(d){let capital=finite(d.capital);if(capital<=0)throw Error('资金必须为正');let rows=d.assets;if(!Array.isArray(rows)||!rows.length||new Set(rows.map(x=>x.code)).size!==rows.length)throw Error('资产需唯一');let sum=0,contributions=rows.map(x=>{if(!x.code)throw Error('资产名称不能为空');let w=finite(x.weight),s=finite(x.shockPct);if(w<0||s< -100)throw Error('无杠杆权重或冲击无效');sum+=w;return {code:x.code,weightPct:w*100,shockPct:s,pnl:capital*w*s/100};});if(Math.abs(sum-1)>1e-8)throw Error('权重必须合计100%');return {type:'shock',capital,assumptions:d.assumptions||[],contributions,pnl:contributions.reduce((s,x)=>s+x.pnl,0),maximumDrawdown:null,note:'用户假设的一次冲击，未含交易成本，不是未来预测或最大回撤'};}
function bond(d){const face=finite(d.face),price=finite(d.price),stock=finite(d.stockPrice),conversion=finite(d.conversionPrice),y=finite(d.yieldPct)/100;if([face,price,stock,conversion].some(x=>x<=0)||y<=-1)throw Error('价格、面值及收益率无效');if(!Array.isArray(d.cashflows)||!d.cashflows.length)throw Error('需要包含本金的债券现金流');let pv=0,mac=0,conv=0;for(const x of d.cashflows){let t=finite(x.years),v=finite(x.amount);if(t<=0||v<=0)throw Error('现金流及时间须为正');let z=v/Math.pow(1+y,t);pv+=z;mac+=t*z;conv+=t*(t+1)*z;}let value=face*stock/conversion;let duration=mac/pv,modified=duration/(1+y);return {type:'bond',conversionValue:value,conversionPremiumPct:(price/value-1)*100,modelStraightBondValue:pv,straightBondPremiumPct:(price/pv-1)*100,doubleLowConvention:price+(price/value-1)*100,macaulayDuration:duration,modifiedDuration:modified,convexity:conv/pv/(1+y)**2,BPV:pv*modified*.0001,note:'现金流按年有效贴现率和年分数；现金流含本金且未计违约和期权。双低采用报价+转股溢价百分点的约定，非通用估值。纯债模型价值不是保本底。输入收益率不是求得YTM；未计算可转债含权久期。'};}
function financial(d){let p=d.current;if(!p||!d.period||!d.sourceUrl)throw Error('需要报告期、来源及当前科目');let warnings=[],checks=[];const get=k=>p[k]==null?null:finite(p[k]);let A=get('assets'),L=get('liabilities'),E=get('equity');if([A,L,E].every(x=>x!==null)){let gap=A-L-E;checks.push({name:'资产－负债－权益',gap,unit:d.unit,status:Math.abs(gap)<=finite(d.tolerance??0.01)?'在容差内':'差异待核对'});}else checks.push({name:'资产负债恒等式',status:'科目缺失'});
 if(get('netProfit')>0&&get('operatingCash')!==null&&get('operatingCash')<0)warnings.push('盈利为正、经营现金净流出：核对营运资本、非现金损益和回款；不是造假证据。');
 if(get('goodwill')!==null&&E!==null){if(E>0)checks.push({name:'商誉/净资产',valuePct:p.goodwill/E*100});else warnings.push('净资产非正，商誉占比不计算。');}
 if(get('cash')!==null&&get('interestDebt')!==null)checks.push({name:'现金与有息债务',cash:p.cash,interestDebt:p.interestDebt,note:'需核对受限现金、期限与资金地域，不能直接净额视为可偿债现金。'});
 for(const k of ['cash','restrictedCash','shortTermDebt','receivables','relatedReceivables'])if(get(k)!==null&&get(k)<0)throw Error('余额不得为负：'+k);
 if(get('restrictedCash')!==null){if(get('cash')===null||p.restrictedCash>p.cash)throw Error('受限资金需对应不低于它的货币资金总额');let available=p.cash-p.restrictedCash;checks.push({name:'扣除已录入受限资金后的现金',gap:available,unit:d.unit});if(get('shortTermDebt')!==null)checks.push({name:'上述现金/短期有息债务',valuePct:p.shortTermDebt>0?available/p.shortTermDebt*100:null});warnings.push('扣除已录入受限资金不代表全部自由现金，期末覆盖率不包含未来现金流和其他到期义务。');}
 if(get('relatedReceivables')!==null){if(get('receivables')===null||p.relatedReceivables>p.receivables)throw Error('关联应收需对应不低于它的应收总额');checks.push({name:'关联应收占应收总额',valuePct:p.receivables>0?p.relatedReceivables/p.receivables*100:null});warnings.push('关联应收不证明客户违约，需要交易实质、回款及客户偿债证据。');}
 if(d.receivableAging){if(!Array.isArray(d.receivableAging)||!d.receivableAging.length||d.receivablesBasis!=='gross'||get('receivables')===null)throw Error('账龄需非空分组及应收原值口径');let names=new Set(),gross=0;for(const row of d.receivableAging){if(!row.label||names.has(row.label)||!row.locator)throw Error('账龄标签须唯一并有附注定位');names.add(row.label);let amount=finite(row.gross),allowance=finite(row.allowance);if(amount<0||allowance<0||allowance>amount)throw Error('账龄余额或准备不合理');gross+=amount;checks.push({name:'账龄 '+row.label+' 计提率',valuePct:amount>0?allowance/amount*100:null});}checks.push({name:'账龄原值合计与应收原值差异',gap:gross-p.receivables,unit:d.unit,status:Math.abs(gross-p.receivables)<=finite(d.tolerance??.01)?'在容差内':'差异待核对'});warnings.push('计提率不证明准备充分，需核对单项计提、分组范围及预期信用损失。');}
 if(d.previous){if(!d.previousPeriod||d.statementScope!==d.previousStatementScope||d.periodBasis!==d.previousPeriodBasis||d.unit!==d.previousUnit)throw Error('跨期需同范围、期间口径和单位');for(const k of ['revenue','receivables','inventory','otherReceivables','construction']){if(p[k]!=null&&d.previous[k]!=null){let prev=finite(d.previous[k]);checks.push({name:k,current:finite(p[k]),previous:prev,changePct:prev>0?(p[k]/prev-1)*100:null});}}}
 return {type:'financial',period:d.period,sourceUrl:d.sourceUrl,checks,warnings,note:'录入数据的恒等式与风险背离检查；未核验原始财报，不判定造假或买卖。期末存量与期间流量不能直接机械比较。'};}


function aligned(d){historical(d);return {dates:d.assets[0].history.map(x=>x.date),returns:d.assets.map(a=>a.history.slice(1).map((x,i)=>x.value/a.history[i].value-1)),weights:d.assets.map(a=>a.weight)};}
function correlationStudy(d){let {dates,returns}=aligned(d),count=returns[0].length,window=d.rollingObservations??60,min=d.minimumObservations??20;if(!Number.isInteger(window)||!Number.isInteger(min)||min<3||window<min)throw Error('滚动窗口和最少样本须为整数，窗口不小于最少样本');
 const matrix=idx=>returns.map(a=>returns.map(b=>ratio(cov(idx.map(i=>a[i]),idx.map(i=>b[i])),sd(idx.map(i=>a[i]))*sd(idx.map(i=>b[i])))));
 let rolling=[];for(let end=window;end<=count;end++)rolling.push({start:dates[end-window],end:dates[end],observations:window,correlations:matrix(Array.from({length:window},(_,i)=>end-window+i))});
 let windows=(d.windows||[]).map(w=>{date(w.start);date(w.end);if(!w.name||w.start>w.end||w.end>d.asOf)throw Error('状态窗口无效');let idx=returns[0].map((_,i)=>i).filter(i=>dates[i]>=w.start&&dates[i+1]<=w.end);return {name:w.name,start:w.start,end:w.end,observations:idx.length,status:idx.length>=min?'历史计算':'样本不足',correlations:idx.length>=min?matrix(idx):null};});
 return {type:'correlationStudy',codes:d.assets.map(x=>x.code),rolling,windows,note:'预先定义窗口的历史相关性，不是危机预测；滚动估计仍可能滞后，零方差留空。窗口收益要求起止均在窗口内。'};}
function rebalance(d){let {dates,returns,weights}=aligned(d),capital=finite(d.capital);if(capital<=0)throw Error('初始资金须为正');let every=d.everyObservations??12;if(!Number.isInteger(every)||every<1)throw Error('定期频率须为正整数观察期');let thresholds=d.thresholdsPct??[3,5];if(!Array.isArray(thresholds)||!thresholds.length||new Set(thresholds).size!==thresholds.length||thresholds.some(x=>finite(x)<=0||x>100))throw Error('阈值为不重复的权重偏离百分点');let cost=d.costs;if(!cost)throw Error('需明确成本，零成本也必须填写');for(let k of ['commissionPct','minimumCommission','spreadBps','slippageBps'])if(finite(cost[k])<0)throw Error('成本不得为负');if(cost.commissionPct>=100||(cost.spreadBps/2+cost.slippageBps)>=10000)throw Error('成本假设超出支持范围');
 const periodicRule=d.periodicRule??'every-observations';if(!['every-observations','month-change'].includes(periodicRule))throw Error('定期规则不支持');if(periodicRule==='month-change'&&d.frequency!=='daily')throw Error('月初信号规则需要日频观察；月频净值不能代替日内执行');
 const overrides=d.costsByCode??{};if(typeof overrides!=='object'||Array.isArray(overrides)||overrides===null||Object.keys(overrides).some(k=>!d.assets.some(a=>a.code===k)))throw Error('逐资产成本须为本次代码对应的对象');
 const allowedCostKeys=['commissionPct','minimumCommission','spreadBps','slippageBps','buyTaxPct','sellTaxPct'];
 const costProfiles=d.assets.map(a=>{let extra=overrides[a.code]??{};if(typeof extra!=='object'||Array.isArray(extra)||extra===null||Object.keys(extra).some(k=>!allowedCostKeys.includes(k)))throw Error('逐资产成本字段无效');let p={...cost,buyTaxPct:cost.buyTaxPct??0,sellTaxPct:cost.sellTaxPct??0,...extra};for(let k of allowedCostKeys)if(finite(p[k])<0)throw Error('逐资产成本不得为负');if(p.commissionPct+Math.max(p.buyTaxPct,p.sellTaxPct)+(p.spreadBps/2+p.slippageBps)/100>=100)throw Error('逐资产综合成本超出支持范围');return {code:a.code,...p};});
 function legsFor(holdings,wealth){return holdings.map((v,j)=>{let p=costProfiles[j],signed=weights[j]*wealth-v,amount=Math.abs(signed),direction=signed>0?'buy':signed<0?'sell':'none';if(amount<=1e-7)return {code:p.code,direction:'none',grossAmount:0,commission:0,spreadCost:0,slippageCost:0,tax:0,totalCost:0};let commission=Math.max(p.minimumCommission,amount*p.commissionPct/100),spreadCost=amount*p.spreadBps/20000,slippageCost=amount*p.slippageBps/10000,tax=amount*(signed>0?p.buyTaxPct:p.sellTaxPct)/100;return {code:p.code,direction,grossAmount:amount,commission,spreadCost,slippageCost,tax,totalCost:commission+spreadCost+slippageCost+tax};});}
 let blocked=d.blockedDates||[];for(let x of blocked){date(x.date);if(!d.assets.some(a=>a.code===x.code)||!dates.includes(x.date))throw Error('不可成交记录须对应资产及观察日');}
 function simulate(name,threshold,periodic){let holdings=weights.map(w=>capital*w),pending=null,totalCost=0,trades=[],path=[{date:dates[0],value:capital}],missed=[];
 for(let i=0;i<returns[0].length;i++){
  holdings=holdings.map((v,j)=>v*(1+returns[j][i]));let pre=holdings.reduce((a,b)=>a+b,0),now=dates[i+1];
  if(pending){let unavailable=blocked.filter(x=>x.date===now).map(x=>x.code);
   if(unavailable.length)missed.push({signalDate:pending,date:now,blockedCodes:unavailable,note:'整笔再平衡跳过，不假设停牌可成交'});
   else {const fees=wealth=>legsFor(holdings,wealth).reduce((sum,leg)=>sum+leg.totalCost,0);
    let high=pre,low=Math.max(1e-9,pre*(1-1e-8));let fh=high+fees(high)-pre,fl=low+fees(low)-pre;
    for(let k=0;k<60&&fl>0;k++){low/=2;fl=low+fees(low)-pre;}
    if(fl>0)throw Error('成本过高，无法完成目标权重交易');
    for(let k=0;k<100;k++){let mid=(low+high)/2;if(mid+fees(mid)>pre)high=mid;else low=mid;}
    let post=(low+high)/2,fee=fees(post),gross=holdings.reduce((sum,v,j)=>sum+Math.abs(weights[j]*post-v),0);
    if(Math.abs(pre-post-fee)>Math.max(1e-5,pre*1e-9))throw Error('最小佣金造成不连续目标，无法可靠求解');
    let costLegs=legsFor(holdings,post);holdings=weights.map(w=>w*post);totalCost+=fee;trades.push({signalDate:pending,date:now,preValue:pre,postValue:post,cost:fee,costLegs,grossTraded:gross,oneWayTurnoverPct:gross/pre/2*100});}
   pending=null;
  }
  let value=holdings.reduce((a,b)=>a+b,0);path.push({date:now,value});let deviation=Math.max(...holdings.map((v,j)=>Math.abs(v/value-weights[j])*100));
  const periodicSignal=periodicRule==='month-change'?now.slice(0,7)!==dates[i].slice(0,7):(i+1)%every===0;
  if(i<returns[0].length-1&&((threshold!==null&&deviation>=threshold)||(periodic&&periodicSignal)))pending=now;
 }
 let peak=capital,dd=0;for(let x of path){peak=Math.max(peak,x.value);dd=Math.max(dd,1-x.value/peak);}let end=path.at(-1).value,years=(Date.parse(dates.at(-1))-Date.parse(dates[0]))/86400000/365.25;
 const costBreakdown={commission:0,spreadCost:0,slippageCost:0,tax:0};let grossTraded=0;
 for(const trade of trades)for(const leg of trade.costLegs){grossTraded+=leg.grossAmount;for(const key of Object.keys(costBreakdown))costBreakdown[key]+=leg[key];}
 const costPaidPctOfInitialCapital=totalCost/capital*100;
 const explanation=trades.length?`本区间执行${trades.length}次再平衡，累计扣除成本${totalCost.toFixed(2)}，相当于初始资金的${costPaidPctOfInitialCapital.toFixed(3)}%。这些是路径中的实际模型扣费，不等于相对零成本路径的期末收益损失。`:'本区间没有执行再平衡，因此本模型未扣再平衡费用；初始建仓费用仍未计入。';
 return {name,endingValue:end,totalReturnPct:(end/capital-1)*100,CAGRPct:(Math.pow(end/capital,1/years)-1)*100,maximumDrawdownPct:dd*100,totalCost,costBreakdown,costPaidPctOfInitialCapital,grossTraded,twoWayTurnoverOfInitialCapital:grossTraded/capital,explanation,tradeCount:trades.length,trades,missed,path};}
 return {type:'rebalance',currency:d.currency,assets:d.assets.map(a=>({code:a.code,sourceUrl:a.sourceUrl,basis:a.basis})),start:dates[0],end:dates.at(-1),capital,periodicRule,periodicRuleExplanation:periodicRule==='month-change'?'新月份首个有数据观察日收盘形成信号，下一观察日收盘执行；未核验完整交易日历，不称月末成交':'每指定观察期收盘形成信号，下一观察日执行；不是日历月',costProfiles,costBasis:'输入研究假设，未自动认证当前或历史有效券商费率与税率；未填写方向税费时按零假设',results:[simulate('买入持有基线',null,false),simulate(periodicRule==='month-change'?'月初信号再平衡':'定期再平衡',null,true),...thresholds.map(x=>simulate('偏离'+x+'个百分点',x,false))],note:'同样本历史回测。收盘信号在下一观察日收盘执行，先承担该期收益，不使用当期收盘信号立即交易。初始建仓成本未计；允许份额拆分，方向税费仅按显式输入假设计算，不含整手限制及基金申赎持有期费率。任一资产不可成交时整笔跳过；成本从组合扣除。最优阈值不能由样本内排名认定。'};
}


function bondResearch(d){
 if(d.priceType!=='full')throw Error('YTM求解需要明确全价，净价必须先加应计利息');
 let base=bond(d),flows=d.cashflows,price=d.price;
 const value=y=>flows.reduce((sum,x)=>sum+x.amount/Math.pow(1+y,x.years),0);
 let low=-.999999,high=1;for(let k=0;k<60&&value(high)>price;k++)high=high*2+1;
 if(value(low)<price||value(high)>price)throw Error('无法在支持范围内求解到期收益率');
 for(let k=0;k<200;k++){let mid=(low+high)/2;if(value(mid)>price)low=mid;else high=mid;}
 let y=(low+high)/2,repriced=value(y);if(Math.abs(repriced-price)>Math.max(1e-7,price*1e-8))throw Error('YTM求解未收敛');
 let scenarios=(d.yieldScenarios||[]).map(x=>{if(!x.name)throw Error('压力情景须命名');let rate=finite(x.rateShiftBps),spread=finite(x.creditSpreadShiftBps),shift=(rate+spread)/10000,newYield=d.yieldPct/100+shift;if(newYield<=-1)throw Error('压力贴现率须大于-100%');let model=value(newYield);return {name:x.name,rateShiftBps:rate,creditSpreadShiftBps:spread,discountYieldPct:newYield*100,modelValue:model,modelChangePct:(model/base.modelStraightBondValue-1)*100,durationConvexityApproxPct:(-base.modifiedDuration*shift+.5*base.convexity*shift**2)*100};});
 return {...base,type:'bondResearch',YTMPct:y*100,YTMRepricingError:repriced-price,scenarios,note:'全价与确定正现金流的年有效YTM，不含转股、强赎回售或违约；期限以输入年分数计。信用利差情景仅改变贴现率，未改变违约概率、恢复率及现金流。纯债重估不是整只可转债价格预测。'};
}
function convertibleTerms(d){date(d.asOf);if(!d.code||!d.sourceUrl)throw Error('条款分析需代码和原文来源');source(d.sourceUrl);date(d.publishedAt);if(d.publishedAt>d.asOf)throw Error('条款公告晚于研究截止日');
 let rows=d.clauses;if(!Array.isArray(rows)||!rows.length||new Set(rows.map(x=>x.kind)).size!==rows.length)throw Error('条款须非空且类型唯一');
 let states=rows.map(x=>{if(!['downwardRevision','call','put'].includes(x.kind))throw Error('条款类型无效');if(typeof x.triggered!=='boolean'&&x.triggered!==null)throw Error('触发状态须明确为是、否或未知');let decision=x.decision??'unknown';if(!['unknown','notExercise','proposed','approved'].includes(decision))throw Error('决策状态无效');if(!x.locator||!x.conditionText)throw Error('需要原文定位和触发条件摘录');if(x.triggered===false&&decision!=='unknown')throw Error('未触发条款不能登记已触发后决策');for(let k of ['triggerDate','decisionDate','implementationDate'])if(x[k]){date(x[k]);if(x[k]>d.asOf)throw Error('状态事件晚于研究截止日');}
 if(x.triggered===true&&!x.triggerDate)throw Error('已触发需触发日期');if(decision!=='unknown'&&!x.decisionDate)throw Error('已知决策需决策日期');if(x.triggerDate&&x.decisionDate&&x.decisionDate<x.triggerDate)throw Error('决策不得早于登记触发日期；预先承诺请另列证据');if(x.implemented!=null&&typeof x.implemented!=='boolean')throw Error('实施状态须为布尔值');if(x.implemented===true&&(decision!=='approved'||!x.implementationDate))throw Error('实施需批准状态及日期');if(x.implementationDate&&x.decisionDate&&x.implementationDate<x.decisionDate)throw Error('实施不得早于决策');
 return {kind:x.kind,triggered:x.triggered,decision,implemented:x.implemented===true,triggerDate:x.triggerDate??null,decisionDate:x.decisionDate??null,implementationDate:x.implemented===true?x.implementationDate:null,conditionText:x.conditionText,locator:x.locator,status:x.implemented===true?'已登记实施':decision==='approved'?'已登记批准，尚未登记实施':decision==='notExercise'?'已登记不行使':decision==='proposed'?'已登记提议，尚未批准':x.triggered===true?'已登记触发，决策待核对':x.triggered===false?'未触发':'触发待核对'};});
 return {type:'convertibleTerms',code:d.code,asOf:d.asOf,publishedAt:d.publishedAt,sourceUrl:d.sourceUrl,states,note:'仅整理使用者提供的原文及状态，不自动查明触发、合法期限或预测公司决策。下修、强赎、回售条件以具体券和现行规则为准；触发不等于实施，不提供交易建议。'};
}

function clone(x){return JSON.parse(JSON.stringify(x));}
function canonical(x){if(x===null||typeof x!=='object')return JSON.stringify(x);if(Array.isArray(x))return '['+x.map(canonical).join(',')+']';return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical(x[k])).join(',')+'}';}
function source(x){try{if(typeof x!=='string'||/[\s\x00-\x1f\x7f]/.test(x))throw Error();let u=new URL(x);if(!['https:','http:'].includes(u.protocol)||!u.hostname||u.username||u.password)throw Error();}catch(_){throw Error('来源须为无凭据的HTTP网址；网址登记不证明原文已核验');}}
function gateway(kind,d){
 if(!d||typeof d!=='object'||Array.isArray(d))throw Error('输入必须为研究对象');
 let gaps=[];
 if(['historical','correlationStudy','rebalance','drawdownStudy','rollingRisk','fundInvestorStudy','benchmarkStudy'].includes(kind)){for(const a of d.assets||[]){source(a.sourceUrl);if(a.availableAt&&date(a.availableAt)>date(d.asOf))throw Error('历史资料可得日超过研究截止日');if(!a.dividendCalendarVerified)gaps.push(a.code+'：分红拆分日历未登记核验');if(!a.availableAt)gaps.push(a.code+'：资料可得日未登记，不能作为时点回测证据');}}
 if(kind==='benchmarkStudy'){source(d.reference?.sourceUrl);if(d.reference?.availableAt&&date(d.reference.availableAt)>date(d.asOf))throw Error('参照数据可得日超过研究日');if(!d.reference?.dividendCalendarVerified)gaps.push('参照对象分红日历未核验');}
 if(kind==='financial'){
  for(const k of ['unit','currency','statementScope','periodBasis','periodEnd','publishedAt','asOf'])if(typeof d[k]!=='string'||!d[k].trim())throw Error('财报缺少口径字段：'+k);
  source(d.sourceUrl);date(d.asOf);date(d.periodEnd);date(d.publishedAt);
  if(d.periodEnd>d.publishedAt||d.publishedAt>d.asOf)throw Error('财报所属期、发布日期与研究截止日不一致');
  if(!['consolidated','parent'].includes(d.statementScope)||!['annual','year-to-date','quarter'].includes(d.periodBasis))throw Error('请明确合并/母公司及年度/累计/单季口径');
  if(d.tolerance!=null&&finite(d.tolerance)<0)throw Error('容差不得为负');
  for(const v of Object.values(d.current||{}))if(v!=null)finite(v);
  if(!Object.values(d.current||{}).some(v=>v!=null))throw Error('至少录入一个财报科目');
  if(d.previous){for(const k of ['previousPeriod','previousPeriodEnd','previousPublishedAt','previousStatementScope','previousPeriodBasis','previousUnit','previousCurrency'])if(!d[k])throw Error('前期资料缺少：'+k);date(d.previousPeriodEnd);date(d.previousPublishedAt);if(d.previousPeriodEnd>=d.periodEnd||d.previousPublishedAt>d.asOf||d.previousPeriodEnd>d.previousPublishedAt||d.previousCurrency!==d.currency)throw Error('前期资料日期或币种不一致');gaps.push('跨期数值未自动判定为同比：仍需核对同一季节和期间长度');}
 }
 if(['bond','bondResearch','convertibleTerms'].includes(kind))gaps.push('现金流与条款由使用者录入，未核验募集说明书；不提供含权信用定价');
 if(kind==='shock')gaps.push('冲击为使用者假设；一次损益不提供未来概率或路径回撤');
 return {status:'结构检查通过，原文未自动核验',gaps};
}
function createSession(){return {version:1,revision:0,kind:null,input:null,results:[],changes:[]};}
function revise(session,kind,input,reason){
 if(!session||session.version!==1||!Array.isArray(session.results)||!Array.isArray(session.changes))throw Error('研究会话无效');
 let next=clone(session),same=next.kind===kind&&canonical(next.input)===canonical(input);
 if(same)return next;
 next.revision++;next.kind=kind;next.input=clone(input);
 next.results=next.results.map(r=>({...r,status:'已失效',invalidatedByRevision:next.revision}));
 next.changes.push({revision:next.revision,reason:reason||'输入前提变更',changedAt:new Date().toISOString()});return next;
}
function invalidate(session,reason){let next=clone(session);next.revision++;next.results=next.results.map(r=>({...r,status:'已失效',invalidatedByRevision:next.revision}));next.input=null;next.changes.push({revision:next.revision,reason:reason||'输入已编辑，等待重新计算',changedAt:new Date().toISOString()});return next;}
function researchAudit(d){
 const states=['available','notPublished','delayed','unauthorized','noTrade','notApplicable','notObtained'];
 if(!d.asOf||!d.timezone)throw Error('需研究截止日与时区');date(d.asOf);try{new Intl.DateTimeFormat('en',{timeZone:d.timezone});}catch(e){throw Error('时区无效');}
 if(!Array.isArray(d.entities)||!d.entities.length)throw Error('需明确对象');let ids=new Set();for(const x of d.entities){if(!x.id||ids.has(x.id)||!x.market||!x.code||!x.name||!x.shareClass)throw Error('对象须有唯一ID、市场、代码、名称及份额/证券类别');ids.add(x.id);}
 if(!Array.isArray(d.observations))throw Error('需观测记录数组');let groups=new Map(),records=[],gaps=[];
 for(const x of d.observations){if(!ids.has(x.entityId)||!x.field||!x.period||!x.basis||!x.unit||!x.currency||!states.includes(x.status))throw Error('观测主键或状态缺失');
 if(x.status==='available'){source(x.sourceUrl);date(x.publishedAt);date(x.availableAt);if(x.publishedAt>x.availableAt||x.availableAt>d.asOf)throw Error('资料发布时间、可得日与截止日冲突');if(!x.locator||!x.version||!['official','issuer','aggregator','user'].includes(x.sourceTier))throw Error('可得观测需原文定位、版本和来源类别');if(x.value==null||!['number','string'].includes(typeof x.value))throw Error('可得观测需数值或文字');if(typeof x.value==='number')finite(x.value);
 }else{if(x.value!=null)throw Error('缺失或不适用状态不能夹带数值');if(!x.reason)throw Error('缺失状态需说明原因');gaps.push({entityId:x.entityId,field:x.field,status:x.status,reason:x.reason});}
 let r=clone(x);records.push(r);let key=JSON.stringify([x.entityId,x.field,x.period,x.basis,x.unit,x.currency]);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);}
 let conflicts=[];for(const [key,all] of groups){let available=all.filter(x=>x.status==='available');if(new Set(available.map(x=>canonical(x.value))).size>1)conflicts.push({key:JSON.parse(key),status:'未裁决',observations:available,note:'保留所有值和版本，不平均、不以多数或最新版本自动裁决。'});}
 let contextGroups=new Map();for(const x of records){let key=JSON.stringify([x.entityId,x.field,x.period]);if(!contextGroups.has(key))contextGroups.set(key,new Set());contextGroups.get(key).add(JSON.stringify([x.basis,x.unit,x.currency]));}
 let incomparable=[...contextGroups].filter(([,v])=>v.size>1).map(([k])=>({key:JSON.parse(k),note:'存在不同口径、单位或币种；未自动换算，不判作同口径数值冲突。'}));
 let capabilityGaps=(d.requestedCapabilities||[]).map(x=>{if(!x.name||!['implemented','partial','unavailable'].includes(x.status)||!x.evidence)throw Error('能力登记需名称、状态和依据');return clone(x);});
 return {type:'researchAudit',entities:clone(d.entities),asOf:d.asOf,timezone:d.timezone,records,gaps,conflicts,incomparable,capabilityGaps,acceptance:{structure:'通过',calculation:'不适用：本入口只核对记录结构',sourceVerification:'未核验',answerQuality:'未评测',humanReview:'未复核'},note:'仅检查使用者登记的对象、日期、缺失和冲突。未自动解析证券、查交易日历、获取原文、实施权限隔离或证明来源真实性。'};
}

function normalizeHoldingsMoney(f){
 if(!Array.isArray(f.holdings))throw Error('需股票持仓数组');
 const monetary=f.holdings.some(h=>h.marketValueCNY!=null)||f.equityMarketValueCNY!=null;
 if(!monetary)return {...f,weightBasis:'使用者提供的权重；无金额勾稽'};
 if(f.currency!=='CNY')throw Error('人民币金额字段不能与其他计价币种混用');
 const cents=v=>{if(typeof v!=='number'||!Number.isFinite(v)||v<0)throw Error('金额须为非负有限数值');let n=Math.round(v*100);if(!Number.isSafeInteger(n)||Math.abs(v*100-n)>.001)throw Error('金额超出逐分精度');return n;};
 const nav=cents(f.netAssetsCNY);if(nav<=0)throw Error('金额计算需要正的整体基金净资产');let total=0;
 let holdings=f.holdings.map(h=>{if(h.marketValueCNY==null)throw Error('有金额时所有已披露证券须提供金额，不能混合口径');const mv=cents(h.marketValueCNY);total+=mv;if(!Number.isSafeInteger(total))throw Error('金额合计超出逐分精度');let actual=mv/nav;if(h.weight!=null&&Math.abs(finite(h.weight)-actual)>.0000501)throw Error('证券权重与公允价值/净资产冲突');return {...h,weight:actual};});
 let equityWeight=f.equityWeight;if(f.equityMarketValueCNY!=null){const equity=cents(f.equityMarketValueCNY);if(total>equity||(f.disclosureScope==='completeEquity'&&total!==equity))throw Error('持仓金额与股票总额不一致');if(equityWeight!=null&&Math.abs(finite(equityWeight)-equity/nav)>.0000501)throw Error('权益总权重与总额/净资产冲突');equityWeight=equity/nav;}
 return {...f,holdings,equityWeight,weightBasis:'人民币公允价值/整体基金净资产逐分重算'};
}

function holdingsStudy(d){
 date(d.asOf);if(!d.currency||!d.industrySystem||!d.industryVersion||!Array.isArray(d.funds)||!d.funds.length)throw Error('需统一币种、行业体系版本和基金列表');let ids=new Set(),allocation=0;
 let funds=d.funds.map(input=>{let f=normalizeHoldingsMoney(input);if(!f.id||ids.has(f.id))throw Error('基金ID为空或重复');ids.add(f.id);date(f.reportDate);date(f.publishedAt);if(f.reportDate>f.publishedAt||f.publishedAt>d.asOf)throw Error('报告日期、发布日期与截止日冲突');source(f.sourceUrl);if(!f.locator||!['top10','completeEquity'].includes(f.disclosureScope)||f.currency!==d.currency)throw Error('需原文定位、股票披露范围及统一计价币种');let equity=finite(f.equityWeight),a=finite(f.allocation);if(equity<0||equity>1||a<0||a>1)throw Error('权重为0到1小数');allocation+=a;if(!Array.isArray(f.holdings))throw Error('需股票持仓数组');if(f.disclosureScope==='top10'&&f.holdings.length>10)throw Error('前十大披露不能录入超过十只证券');let keys=new Set(),weight=0,industries={};const holdings=f.holdings.map(h=>{if(!h.market||!h.code||!h.shareClass||!h.name)throw Error('股票需市场、代码、证券类别和名称');if(h.securityNamespace&&(!['CN-equity','HK-equity'].includes(h.securityNamespace)||(h.securityNamespace==='CN-equity'&&!['SSE','SZSE','BSE','CN-exchange-unresolved'].includes(h.market))||(h.securityNamespace==='HK-equity'&&!['HKEX','HK','HK-exchange-unresolved'].includes(h.market))))throw Error('证券命名空间与市场冲突');let key=JSON.stringify([h.securityNamespace||h.market,h.code,h.shareClass]);if(keys.has(key))throw Error('同一基金证券主键重复，请先核对合并');keys.add(key);let w=finite(h.weight);if(w<0||w>1)throw Error('持仓权重为净资产占比小数');weight+=w;let industry=h.industry||'未分类';industries[industry]=(industries[industry]||0)+w;return {...clone(h),key};});if(weight>equity+1e-8)throw Error('股票持仓合计超过股票总仓位');if(f.disclosureScope==='completeEquity'&&Math.abs(weight-equity)>1e-8)throw Error('完整股票持仓合计须与股票总仓位一致；有差额请登记为局部披露');
 let sorted=[...holdings].sort((a,b)=>b.weight-a.weight),top10Weight=sorted.slice(0,10).reduce((t,h)=>t+h.weight,0),marketWeights={};for(const h of holdings)marketWeights[h.market]=(marketWeights[h.market]||0)+h.weight;let unknown=Math.max(0,equity-weight);return {weightBasis:f.weightBasis,portfolioScope:f.portfolioScope||'notDeclared',fundShareClasses:f.fundShareClasses||null,segments:f.segments||null,top10Weight,otherDisclosedEquityWeight:Math.max(0,weight-top10Weight),marketWeights,disclosedSecurityHHI:equity>0?holdings.reduce((t,h)=>t+(h.weight/equity)**2,0):null,id:f.id,allocation:a,reportDate:f.reportDate,publishedAt:f.publishedAt,disclosureScope:f.disclosureScope,equityWeight:equity,disclosedWeight:weight,unknownEquityWeight:unknown,nonEquityWeight:1-equity,coveragePct:equity>0?weight/equity*100:null,industries,disclosedIndustryHHI:equity>0&&Object.entries(industries).some(([k,w])=>k!=='未分类'&&w>0)?Object.entries(industries).filter(([k])=>k!=='未分类').reduce((sum,[,w])=>sum+(w/equity)**2,0):null,holdings};});
 if(Math.abs(allocation-1)>1e-8)throw Error('基金组合权重合计须为1');
 let pairs=[];for(let i=0;i<funds.length;i++)for(let j=i+1;j<funds.length;j++){let a=funds[i],b=funds[j];if(a.reportDate!==b.reportDate){pairs.push({a:a.id,b:b.id,status:'报告期不同，不直接比较',observedOverlapWeight:null});continue;}let topA=new Set([...a.holdings].sort((x,y)=>y.weight-x.weight).slice(0,10).map(h=>h.key)),topB=new Set([...b.holdings].sort((x,y)=>y.weight-x.weight).slice(0,10).map(h=>h.key)),map=new Map(b.holdings.map(h=>[h.key,h])),common=a.holdings.filter(h=>map.has(h.key)).map(h=>({market:h.market,code:h.code,shareClass:h.shareClass,securityNamespace:h.securityNamespace||null,marketB:map.get(h.key).market,weightA:h.weight,weightB:map.get(h.key).weight,overlapWeight:Math.min(h.weight,map.get(h.key).weight),inTop10A:topA.has(h.key),inTop10B:topB.has(h.key),overlapSegment:topA.has(h.key)&&topB.has(h.key)?'bothTop10':!topA.has(h.key)&&!topB.has(h.key)?'bothOther':'mixed'}));let overlapBySegment={bothTop10:0,bothOther:0,mixed:0};for(const h of common)overlapBySegment[h.overlapSegment]+=h.overlapWeight;let overlap=common.reduce((sum,h)=>sum+h.overlapWeight,0);pairs.push({a:a.id,b:b.id,status:a.unknownEquityWeight+b.unknownEquityWeight>1e-8?'局部披露：仅为已知重合下界':'完整股票披露',overlapBySegment,observedOverlapWeight:overlap,conservativeUpperWeight:Math.min(a.equityWeight,b.equityWeight,overlap+a.unknownEquityWeight+b.unknownEquityWeight),common});}
 let positions=new Map(),industries={},unknown=0,nonEquity=0;for(const f of funds){unknown+=f.allocation*f.unknownEquityWeight;nonEquity+=f.allocation*f.nonEquityWeight;for(const h of f.holdings){let contribution=f.allocation*h.weight;if(!positions.has(h.key))positions.set(h.key,{market:h.market,code:h.code,shareClass:h.shareClass,securityNamespace:h.securityNamespace||null,name:h.name,weight:0});positions.get(h.key).weight+=contribution;let k=h.industry||'未分类';industries[k]=(industries[k]||0)+contribution;}}
 return {type:'holdingsStudy',funds,pairs,portfolio:{positions:[...positions.values()],industries,unknownEquityWeight:unknown,nonEquityWeight:nonEquity,reportDates:[...new Set(funds.map(f=>f.reportDate))],disclosedIndustryHHI:Object.entries(industries).some(([k,w])=>k!=='未分类'&&w>0)?Object.entries(industries).filter(([k])=>k!=='未分类').reduce((sum,[,w])=>sum+w*w,0):null},note:'权重均相对基金或组合净资产；有公允价值时由金额重算，可能与已舍入的显示权重合计不同；两两重合为相同证券权重取最小值求和；有明确CN-equity/HK-equity命名空间时以命名空间、代码、证券类别为主键，境内不同交易所不按代码猜，未声明时按市场主键；按净资产权重排序拆成双方前十大、双方其余持仓、一方前十大一方其余三类，权重相同按输入报告顺序。HHI只计已披露行业，未知仓位不归零、不归现金，未分类不等于真实同一行业。不同报告期组合仅为混合快照，不能称当前真实持仓；不推断交易流水、主动调仓、完整风险或未来收益。'};
}
function drawdownSummary(episodes){
 return [[0,5],[5,10],[10,20],[20,null]].map(([lower,upper])=>{let rows=episodes.filter(e=>e.depthPct>=lower&&(upper===null||e.depthPct<upper)),recovered=rows.filter(e=>e.recoveryDate!==null),open=rows.filter(e=>e.recoveryDate===null);let periods=recovered.map(e=>e.underwaterCalendarDays).sort((a,b)=>a-b),n=periods.length;
 return {depthLowerPct:lower,depthUpperExclusivePct:upper,episodeCount:rows.length,recoveredCount:n,rightCensoredCount:open.length,observedRecoveredFraction:rows.length?n/rows.length:null,meanRecoveredCalendarDays:n?mean(periods):null,medianRecoveredCalendarDays:n?(n%2?periods[(n-1)/2]:(periods[n/2-1]+periods[n/2])/2):null,minimumCensoredFollowupCalendarDays:open.length?Math.min(...open.map(e=>e.underwaterCalendarDays)):null,note:'截至样本末已修复占比，不是未来修复概率；时长均值仅条件于已修复事件，有删失与选择偏差，未修复事件不计为0。'};});
}
function drawdownStudy(d){
 historical(d);const dates=d.assets[0].history.map(x=>x.date);const days=(a,b)=>(Date.parse(b)-Date.parse(a))/86400000;
 function analyze(code,values){let peakIndex=0,active=null,episodes=[],path=[];
 function finish(end,recovered){let peak=values[active.peakIndex],trough=values[active.troughIndex];return {peakDate:dates[active.peakIndex],firstBelowPeakDate:dates[active.startIndex],troughDate:dates[active.troughIndex],recoveryDate:recovered?dates[end]:null,lastObservedDate:dates[end],status:recovered?'已修复':'截至样本末未修复',depthPct:(1-trough/peak)*100,requiredRiseFromTroughPct:(peak/trough-1)*100,currentGapPct:(1-values[end]/peak)*100,requiredRiseFromLastPct:Math.max(0,(peak/values[end]-1)*100),underwaterObservations:end-active.peakIndex,underwaterCalendarDays:days(dates[active.peakIndex],dates[end]),troughToRecoveryObservations:recovered?end-active.troughIndex:null,troughToRecoveryCalendarDays:recovered?days(dates[active.troughIndex],dates[end]):null};}
 for(let i=0;i<values.length;i++){if(values[i]>=values[peakIndex]){if(active){episodes.push(finish(i,true));active=null;}peakIndex=i;}else{if(!active)active={peakIndex,startIndex:i,troughIndex:i};else if(values[i]<values[active.troughIndex])active.troughIndex=i;}path.push({date:dates[i],drawdownPct:(1-values[i]/values[peakIndex])*100});}
 if(active)episodes.push(finish(values.length-1,false));return {code,start:dates[0],end:dates.at(-1),observations:values.length,episodes,severitySummary:drawdownSummary(episodes),maximumDrawdownPct:episodes.length?Math.max(...episodes.map(x=>x.depthPct)):0,recoveredEpisodeCount:episodes.filter(x=>x.recoveryDate!==null).length,unrecoveredEpisodeCount:episodes.filter(x=>x.recoveryDate===null).length,path};}
 let portfolio=[1];for(let i=1;i<dates.length;i++)portfolio.push(portfolio.at(-1)*(1+d.assets.reduce((sum,a)=>sum+a.weight*(a.history[i].value/a.history[i-1].value-1),0)));
 return {type:'drawdownStudy',assets:d.assets.map(a=>analyze(a.code,a.history.map(x=>x.value))),portfolio:analyze('组合（每期无成本恢复目标权重）',portfolio),note:'历史高水位回撤，修复定义为观察值达到或超过原高点；相同高点取最近一次日期。只观察采样日期，不识别期间内低点；观察期数不是交易日数。末期未修复为右删失，不能剔除后推断回本概率；所需涨幅仅为算术关系，不预测修复时间。样本起点以前的高点未知；组合沿用每期无成本恢复权重假设，非真实账户收益。'};
}
function rollingRisk(d){
 const full=historical(d);let months=finite(d.windowMonths??12);if(!Number.isInteger(months)||months<1||months>120)throw Error('滚动窗口须为1至120整数月');
 const dates=d.assets[0].history.map(x=>x.date),points=[];
 for(let i=1;i<dates.length;i++){if(i<dates.length-1&&dates[i].slice(0,7)===dates[i+1].slice(0,7))continue;
 let end=dates[i],cut=new Date(end+'T00:00:00Z'),day=cut.getUTCDate();cut.setUTCDate(1);cut.setUTCMonth(cut.getUTCMonth()-months);cut.setUTCDate(Math.min(day,new Date(Date.UTC(cut.getUTCFullYear(),cut.getUTCMonth()+1,0)).getUTCDate()));let cutoff=cut.toISOString().slice(0,10);
 let prior=-1;for(let j=0;j<=i;j++){if(dates[j]<=cutoff)prior=j;else break;}
 if(prior<0||i-prior<3){points.push({end,status:'窗口历史不足',requestedStart:cutoff});continue;}
 let input={...d,assets:d.assets.map(a=>({...a,history:a.history.slice(prior,i+1)}))},r=historical(input);
 points.push({end,status:'已计算',requestedStart:cutoff,start:r.start,observations:r.observations,assets:r.assets,portfolio:r.portfolio});}
 return {type:'rollingRisk',start:full.start,end:full.end,assets:full.assets,windowMonths:months,points,note:'每月最后一个已记录观察日及样本末日输出；末月可能尚未结束。窗口起点取目标日期或之前最近观察日，实际区间另列。每点仅用该点及以前收益，不含之后收益；数据本身可能是当前修订历史，未证明当时可得。窗口内回撤不包含起点以前高点。无完整窗口不填零。相关窗口重叠，不能视为独立样本或未来风险预测。',limitations:full.limitations};
}
function fundInvestorStudy(d){
 if(d.navIncludesOperatingFees!==true)throw Error('须明确净值已计提运作费用，避免重复扣费');if(!['current-fee-scenario','historically-verified'].includes(d.feeBasis))throw Error('须区分现行费率情景与历史已核验费率');
 let capital=finite(d.cashOutlay);if(capital<=0)throw Error('投入资金须为正');let study=historical({...d,riskFreeAnnualPct:0}),start=study.start,end=study.end,holdingDays=(Date.parse(end)-Date.parse(start))/86400000;
 const tier=(rows,value,label)=>{if(!Array.isArray(rows)||!rows.length)throw Error(label+'费率缺失');let previous=0;for(let i=0;i<rows.length;i++){let r=rows[i];finite(r.lower);if(r.lower!==previous||r.lower<0)throw Error(label+'分档须从0连续且无重叠');if(r.upper!==null){finite(r.upper);if(r.upper<=r.lower)throw Error(label+'分档范围无效');previous=r.upper;}else{if(i!==rows.length-1)throw Error(label+'无上限仅可在末档');previous=Infinity;}if(r.ratePct!=null){finite(r.ratePct);if(r.ratePct<0||r.ratePct>=100||r.flatAmount!=null)throw Error(label+'费率无效');}else{finite(r.flatAmount);if(r.flatAmount<0)throw Error(label+'固定金额无效');}}
 let found=rows.find(r=>value>=r.lower&&(r.upper===null||value<r.upper));if(!found)throw Error(label+'没有覆盖所需金额或天数');return found;};
 let assets=d.assets.map(a=>{let f=a.fees;if(!f||!f.sourceUrl||!f.observedAt)throw Error('费率须有来源和观察日期');source(f.sourceUrl);date(f.observedAt);if(f.observedAt>d.asOf)throw Error('费率观察日超过研究日');if(d.feeBasis==='historically-verified'){date(f.effectiveFrom);date(f.effectiveThrough);}if(d.feeBasis==='historically-verified'&&(!f.effectiveFrom||f.effectiveFrom>start||!f.effectiveThrough||f.effectiveThrough<end))throw Error('历史费率有效期未覆盖区间');
 let entry=tier(f.subscription,capital,'申购'),exit=tier(f.redemption,holdingDays,'赎回');if(exit.ratePct==null)throw Error('赎回须明确费率');let invested=entry.ratePct!=null?capital/(1+entry.ratePct/100):capital-entry.flatAmount;if(invested<=0)throw Error('申购费不小于投入金额');let ratio=a.history.at(-1).value/a.history[0].value,grossTerminal=invested*ratio,redemptionFee=grossTerminal*exit.ratePct/100,netTerminal=grossTerminal-redemptionFee,years=holdingDays/365.25;
 return {code:a.code,start,end,holdingDays,cashOutlay:capital,invested,subscriptionFee:capital-invested,navPathReturnPct:(ratio-1)*100,redemptionFee,netTerminal,pnl:netTerminal-capital,investorReturnPct:(netTerminal/capital-1)*100,investorCAGRPct:years>0?(Math.pow(netTerminal/capital,1/years)-1)*100:null,feeDragTerminal:capital*ratio-netTerminal,fees:f,feeBasis:d.feeBasis,operatingFeesDeductedAgain:false};});
 return {type:'fundInvestorStudy',start,end,assets,note:'每只基金分别投入相同示例本金；不是实际账户或组合权重。净值总收益已含运作费，不重复扣管理、托管或销售服务费；另计申购及赎回。比例申购采用外扣法，固定费用从本金扣除；未模拟确认日、渠道优惠、份额及金额舍入、转换费用、申赎限制、税务或现金分红不再投。现行费率应用历史路径只为情景对照，不能冒称历史实际收益或未来收益。费拖累终值差包括申购费对应的历史收益损失，不等于已收费用简单相加。'};
}
function benchmarkStudy(d){
 if(!d.reference||!['comparison-reference','declared-benchmark'].includes(d.reference.role))throw Error('须明确参照对象及其角色；同伴基金不是合同基准');if(d.reference.role==='declared-benchmark'&&(typeof d.reference.definition!=='string'||!d.reference.definition.trim()))throw Error('声明基准须登记定义，仍不证明原文已核验');
 let all=[...d.assets,d.reference],count=all.length;historical({...d,assets:all.map(a=>({...a,weight:1/count}))});const dates=d.reference.history.map(h=>h.date),periods={daily:252,monthly:12}[d.frequency],returns=h=>h.slice(1).map((x,i)=>x.value/h[i].value-1),b=returns(d.reference.history),epsilon=1e-12;
 const safely=(x,y)=>Math.abs(y)>epsilon?x/y:null;
 function stats(f,reference){let n=f.length,excess=f.map((r,i)=>r-reference[i]),positive=excess.filter(x=>x>epsilon),negative=excess.filter(x=>x< -epsilon),ties=n-positive.length-negative.length,annualTE=sd(excess)*Math.sqrt(periods),annualMeanExcess=mean(excess)*periods;
 const conditional=sign=>{let index=reference.map((r,i)=>({r,i})).filter(x=>sign==='up'?x.r>epsilon:x.r< -epsilon).map(x=>x.i);if(!index.length)return {observations:0,outperformanceCount:0,historicalOutperformanceFrequencyPct:null,arithmeticCapturePct:null,geometricAnnualizedCapturePct:null};let x=index.map(i=>f[i]),y=index.map(i=>reference[i]),gx=Math.pow(x.reduce((v,r)=>v*(1+r),1),periods/index.length)-1,gy=Math.pow(y.reduce((v,r)=>v*(1+r),1),periods/index.length)-1;
 return {observations:index.length,outperformanceCount:index.filter(i=>f[i]-reference[i]>epsilon).length,historicalOutperformanceFrequencyPct:index.filter(i=>f[i]-reference[i]>epsilon).length/index.length*100,arithmeticCapturePct:safely(mean(x)*100,mean(y)),geometricAnnualizedCapturePct:safely(gx*100,gy),conditionalFundAnnualReturnPct:gx*100,conditionalReferenceAnnualReturnPct:gy*100};};
 let fv=f.reduce((v,r)=>v*(1+r),1),bv=reference.reduce((v,r)=>v*(1+r),1);
 return {observations:n,outperformanceCount:positive.length,underperformanceCount:negative.length,tieCount:ties,historicalOutperformanceFrequencyPct:positive.length/n*100,meanPositiveExcessPct:positive.length?mean(positive)*100:null,meanNegativeExcessPct:negative.length?mean(negative)*100:null,excessWinLossRatio:positive.length&&negative.length?safely(mean(positive),Math.abs(mean(negative))):null,meanPeriodExcessPct:mean(excess)*100,periodExcessStdPct:sd(excess)*100,annualArithmeticExcessPct:annualMeanExcess*100,annualTrackingErrorPct:annualTE*100,informationRatio:annualTE>epsilon?annualMeanExcess/annualTE:null,cumulativeReturnDifferencePercentagePoints:(fv-bv)*100,relativeWealthReturnPct:(fv/bv-1)*100,upMarket:conditional('up'),downMarket:conditional('down'),flatReferenceCount:reference.filter(x=>Math.abs(x)<=epsilon).length};}
 let windows=d.rollingWindows||[d.rollingObservations??(d.frequency==='monthly'?12:252)];if(!Array.isArray(windows)||!windows.length||windows.length>24||new Set(windows).size!==windows.length||windows.some(w=>!Number.isInteger(finite(w))||w<3||w>10000))throw Error('滚动观察数须为3至10000唯一整数，最多24个窗口');let window=windows[0];
 let assets=d.assets.map(a=>{let f=returns(a.history),rolling=[];for(const w of windows)for(let i=w-1;i<f.length;i++){let r=stats(f.slice(i-w+1,i+1),b.slice(i-w+1,i+1));rolling.push({windowObservations:w,start:dates[i-w+1],end:dates[i+1],...r});}let informationRatioSignChanges=[];for(let i=1;i<rolling.length;i++){let previous=rolling[i-1],current=rolling[i];if(previous.windowObservations===current.windowObservations&&previous.informationRatio!=null&&current.informationRatio!=null&&((previous.informationRatio>epsilon&&current.informationRatio< -epsilon)||(previous.informationRatio< -epsilon&&current.informationRatio>epsilon)))informationRatioSignChanges.push({windowObservations:current.windowObservations,previousEnd:previous.end,end:current.end,from:previous.informationRatio,to:current.informationRatio,direction:previous.informationRatio>0?'正转负':'负转正'});}return {code:a.code,...stats(f,b),periodReturns:f.map((x,i)=>({start:dates[i],end:dates[i+1],fundReturnPct:x*100,referenceReturnPct:b[i]*100,excessPercentagePoints:(x-b[i])*100})),rolling,informationRatioSignChanges};});
 return {type:'benchmarkStudy',start:dates[0],end:dates.at(-1),frequency:d.frequency,reference:{code:d.reference.code,role:d.reference.role,definition:d.reference.definition||null,sourceUrl:d.reference.sourceUrl},rollingObservations:window,rollingWindows:windows,assets,note:'超额为每期简单收益之差；累计收益差（百分点）与相对财富收益分别展示。信息比率为每期超额均值年化/样本超额标准差年化。捕捉率分别列条件算术均值比与条件几何年化收益比，后者不是完整日历期间年化；基准零收益期不放入涨跌子样本。无相应样本、无负超额或零分母返回null。历史跑赢频次不是未来胜率，同伴参照不是合同基准；不剥离行业和风格贝塔，不代表纯阿尔法或管理能力，也不输出买卖结论。相对参照的超额波动不是自动核验的合同跟踪误差。正负转变只记录相邻非零、非null信息比率的跨零事件，不推断未来趋势。重叠滚动窗口不独立。'};
}

function industryStudy(d){
 date(d.asOf);if(d.currency!=='CNY'||!Array.isArray(d.funds)||!d.funds.length||d.funds.length>100||new Set(d.funds.map(f=>JSON.stringify([f.id,f.reportDate]))).size!==d.funds.length)throw Error('需要人民币口径、唯一基金/报告期及最多100份行业报告');
 const cents=v=>{let t=String(v);if(!/^\d+(\.\d{1,2})?$/.test(t))throw Error('金额必须非负且最多两位小数');let [whole,part='']=t.split('.'),n=Number(whole)*100+Number(part.padEnd(2,'0'));if(!Number.isSafeInteger(n))throw Error('金额超出逐分精度范围');return n;};
 const funds=d.funds.map(f=>{source(f.sourceUrl);date(f.reportDate);date(f.publishedAt);if(f.reportDate>f.publishedAt||f.publishedAt>d.asOf)throw Error('报告尚未发布或日期冲突');if(f.currency!=='CNY'||!f.id||!f.taxonomy||!f.taxonomyVersion||!Array.isArray(f.sectors)||!f.sectors.length)throw Error('缺少行业口径');let nav=cents(f.netAssetsCNY),equity=cents(f.equityMarketValueCNY);if(!nav||!equity)throw Error('净资产及权益总额须为正');let keys=new Set(),sum=0;
 let sectors=f.sectors.map(x=>{if(!x.key||keys.has(x.key)||!x.name||typeof x.isUnclassified!=='boolean'||!Array.isArray(x.components)||!x.components.length||x.components.some(c=>!c.locator))throw Error('行业标识、分类状态或原文位置缺失');keys.add(x.key);let value=cents(x.marketValueCNY);sum+=value;if(!Number.isSafeInteger(sum))throw Error('行业合计超出精度');if(x.components.reduce((t,c)=>t+cents(c.marketValueCNY),0)!==value)throw Error('行业分表金额不守恒');return {...x,navWeight:value/nav,equityWeight:value/equity};});
 if(sum!==equity)throw Error('行业金额与权益总额不一致');let known=sectors.filter(x=>!x.isUnclassified),unknown=sectors.filter(x=>x.isUnclassified).reduce((t,x)=>t+x.equityWeight,0),classified=1-unknown,lower=known.reduce((t,x)=>t+x.equityWeight**2,0),largest=Math.max(0,...known.map(x=>x.equityWeight));
 return {id:f.id,reportDate:f.reportDate,publishedAt:f.publishedAt,taxonomy:f.taxonomy,taxonomyVersion:f.taxonomyVersion,equityWeight:equity/nav,classifiedEquityCoverage:classified,unclassifiedEquityWeight:unknown,unclassifiedNAVWeight:unknown*equity/nav,equityIndustryHHI:unknown===0?lower:null,equityIndustryHHIBounds:known.length?{lower,upper:lower+2*largest*unknown+unknown**2}:null,top3ClassifiedEquityWeight:[...known].sort((a,b)=>b.equityWeight-a.equityWeight).slice(0,3).reduce((t,x)=>t+x.equityWeight,0),sectors};});
 return {type:'industryStudy',funds,aggregationStatus:'未合并：原文行业分类规则版本未核验，不进行跨基金行业排名',note:'HHI使用行业金额除以权益总额后的权重平方和，非净资产权重平方和；未分类非零时不提供精确HHI。下界为已分类权重平方和，上界假设全部未分类并入最大已知行业；下界仅为保守数学界，不是假定未知行业实际无限分散。每行是对应报告期快照；多期并列不证明分类规则恒定，也不是当前持仓、历史集中度与未来回撤关联，未完成中信一级行业、同风格中位数或Brinson归因。'};
}


function holdingsChange(d){
 date(d.asOf);if(d.currency!=='CNY'||!Array.isArray(d.reports)||d.reports.length!==2)throw Error('跨期分析需同基金两份人民币完整报告');
 let reports=d.reports;if(reports[0].id!==reports[1].id||reports[0].reportDate>=reports[1].reportDate||reports.some(f=>f.disclosureScope!=='completeEquity'))throw Error('报告须同基金、日期递增且均为完整权益');
 const snapshots=reports.map(f=>{let nav=finite(f.netAssetsCNY),total=finite(f.equityMarketValueCNY);if(nav<=0||total<0)throw Error('缺少净资产及权益金额');let sum=0,holdings=f.holdings.map(h=>{let value=finite(h.marketValueCNY),cents=Math.round(value*100);if(value<0||!Number.isSafeInteger(cents)||Math.abs(value*100-cents)>.001)throw Error('权益金额逐分精度无效');sum+=cents;if(!Number.isSafeInteger(sum))throw Error('金额合计超出精度');if(h.quantity!=null&&(!Number.isSafeInteger(h.quantity)||h.quantity<0))throw Error('股数须为非负安全整数');return {...h,weight:value/nav};});if(sum!==Math.round(total*100))throw Error('权益明细与金额合计不一致');return holdingsStudy({asOf:d.asOf,currency:'CNY',industrySystem:'unclassified',industryVersion:'none',funds:[{...f,allocation:1,equityWeight:total/nav,holdings}]}).funds[0];});
 const before=snapshots[0],after=snapshots[1],left=new Map(before.holdings.map(h=>[h.key,h])),right=new Map(after.holdings.map(h=>[h.key,h])),keys=new Set([...left.keys(),...right.keys()]);
 let rows=[...keys].map(key=>{let x=left.get(key),y=right.get(key),h=y||x;return {key,market:h.market,securityNamespace:h.securityNamespace||null,code:h.code,shareClass:h.shareClass,name:h.name,beforeWeight:x?.weight||0,afterWeight:y?.weight||0,weightChangePercentagePoints:((y?.weight||0)-(x?.weight||0))*100,beforeQuantity:x?.quantity??null,afterQuantity:y?.quantity??null,observedQuantityChange:x&&y&&x.quantity!=null&&y.quantity!=null?y.quantity-x.quantity:null,status:!x?'期末新出现':!y?'期末不再披露':'两期均披露',beforeLocator:x?.locator||null,afterLocator:y?.locator||null};});
 rows.sort((a,b)=>Math.abs(b.weightChangePercentagePoints)-Math.abs(a.weightChangePercentagePoints));
 return {type:'holdingsChange',id:before.id,start:before.reportDate,end:after.reportDate,beforePublishedAt:before.publishedAt,afterPublishedAt:after.publishedAt,rows,newlyObservedCount:rows.filter(r=>r.status==='期末新出现').length,noLongerObservedCount:rows.filter(r=>r.status==='期末不再披露').length,bothObservedCount:rows.filter(r=>r.status==='两期均披露').length,equityWeightChangePercentagePoints:(after.equityWeight-before.equityWeight)*100,observedAbsoluteWeightChangePercentagePoints:rows.reduce((t,r)=>t+Math.abs(r.weightChangePercentagePoints),0),note:'两份完整权益报告期末快照差异，金额权重相对各期整体基金净资产。期末新出现/不再披露不是可验证的买卖时点；数量变化也可能来自送转、拆合股、转股等公司行为。权重变动含价格、汇率、净资产与申赎变化，绝对权重变动和不是交易换手率。没有交易流水、公司行为及期间价格，不拆主动调仓与被动漂移，不计算已实现盈亏、收益贡献或交易胜率。'};
}


function fundProfitStudy(d){
 date(d.asOf);if(!Array.isArray(d.funds)||!d.funds.length||d.funds.length>100||new Set(d.funds.map(f=>JSON.stringify([f.id,f.periodStart,f.periodEnd]))).size!==d.funds.length)throw Error('利润表须为唯一基金/期间，最多100份');
 const cents=v=>{let t=String(v);if(!/^-?\d+(\.\d{1,2})?$/.test(t))throw Error('金额须为带符号的元、最多两位小数');let n=Math.round(Number(t)*100);if(!Number.isSafeInteger(n))throw Error('金额超出逐分精度');return n;};
 const funds=d.funds.map(f=>{source(f.sourceUrl);for(const k of ['periodStart','periodEnd','publishedAt','reportDate'])date(f[k]);if(!f.id||f.currency!=='CNY'||f.statementScope!=='fund-all-share-classes'||f.periodStart>f.periodEnd||f.periodEnd!==f.reportDate||f.reportDate>f.publishedAt||f.publishedAt>d.asOf)throw Error('利润表范围、报告/发布日期不一致');
 const items=list=>{if(!Array.isArray(list)||!list.length||new Set(list.map(x=>x.name)).size!==list.length)throw Error('利润表科目为空/重复');return list.map(x=>{if(!x.name||!x.locator)throw Error('利润表缺原文科目/定位');return {...x,amountCents:cents(x.amountCNY)};});};let income=items(f.income),expenses=items(f.expenses),investmentDetails=items(f.investmentDetails);if(income.length!==5||expenses.length!==8||!/^2[.．]投资收益/.test(income[1].name))throw Error('收支主科目范围或投资收益父项位置不正确');let totals={};for(const k of ['income','expenses','profitBeforeTax','incomeTax','netProfit']){let x=f.totals?.[k];if(!x?.locator||!x.name)throw Error('缺少利润表总额与页码');totals[k]={...x,amountCents:cents(x.amountCNY)};}
 const sum=xs=>{let n=xs.reduce((t,x)=>t+x.amountCents,0);if(!Number.isSafeInteger(n))throw Error('合计超出精度');return n;};if(sum(income)!==totals.income.amountCents||sum(expenses)!==totals.expenses.amountCents||sum(investmentDetails)!==income[1].amountCents||totals.income.amountCents-totals.expenses.amountCents!==totals.profitBeforeTax.amountCents||totals.profitBeforeTax.amountCents-totals.incomeTax.amountCents!==totals.netProfit.amountCents)throw Error('收入/投资子项/费用/税前及净利润勾稽失败');
 return {id:f.id,periodStart:f.periodStart,periodEnd:f.periodEnd,reportDate:f.reportDate,publishedAt:f.publishedAt,income,investmentDetails,expenses,totals,reconciliation:'全部逐分一致'};});
 return {type:'fundProfitStudy',funds,note:'基金整体会计利润表，非单一份额类投资者回报。投资收益父项已经包含股票差价、股利等子项，不重复相加。公允价值变动含未实现估值变化；股利不额外增加除息前账户总资产。费用已计入基金资产和净值，不能再从净值收益重复扣除。净利润/期末净资产不是时间加权收益率；此表不提供交易收益归因、经理阿尔法或未来收益。报表费用不是二级市场佣金、个人申赎费用，也不代表全部交易冲击成本。'};
}

const raw={fundProfitStudy,holdingsChange,industryStudy,benchmarkStudy,fundInvestorStudy,rollingRisk,drawdownStudy,holdingsStudy,researchAudit,historical,shock,bond,financial,correlationStudy,rebalance,bondResearch,convertibleTerms};
function finiteResult(value){if(typeof value==='number'&&!Number.isFinite(value))throw Error('计算结果溢出或包含非有限数值，不能输出为有效研究结果');if(value&&typeof value==='object')for(const entry of Object.values(value))finiteResult(entry);}
function evaluate(kind,d){if(!raw[kind])throw Error('未知测算类型');let audit=gateway(kind,d),result=raw[kind](d);finiteResult(result);return {...result,engineVersion:'3.7',inputSnapshot:clone(d),inputAudit:audit,createdAt:new Date().toISOString(),evidenceStatus:'使用者输入；未自动核验原文',acceptance:result.acceptance||{structure:'通过',calculation:'已执行；本次结果未独立复算',sourceVerification:'未核验',answerQuality:'未评测',humanReview:'未复核'}};}
function calculate(session,kind,input){let result=evaluate(kind,input),next=revise(session,kind,input,'重新计算使用当前前提');next.results.push({revision:next.revision,kind,status:'当前',result});return next;}

function inputTemplate(kind){
 const meta={templateNotice:'空白输入模板，不含真实数据；请填入核验后的资料，不要将示例字段视为证据。'};
 const history={...meta,asOf:'',frequency:'daily',currency:'CNY',riskFreeAnnualPct:null,assets:[{code:'',weight:null,currency:'CNY',basis:'total-return',sourceUrl:'',availableAt:'',dividendCalendarVerified:false,history:[]}]};
 const templates={fundProfitStudy:{...meta,asOf:'',funds:[]},holdingsChange:{...meta,asOf:'',currency:'CNY',reports:[]},industryStudy:{...meta,asOf:'',currency:'CNY',funds:[]},benchmarkStudy:{...history,frequency:'monthly',rollingObservations:12,rollingWindows:[6,12],reference:{code:'',role:'comparison-reference',currency:'CNY',basis:'total-return',sourceUrl:'',history:[]}},fundInvestorStudy:{...history,cashOutlay:null,navIncludesOperatingFees:true,feeBasis:'current-fee-scenario',assets:history.assets.map(a=>({...a,fees:{sourceUrl:'',observedAt:'',subscription:[{lower:0,upper:null,ratePct:null}],redemption:[{lower:0,upper:null,ratePct:null}]}}))},rollingRisk:{...history,windowMonths:12},drawdownStudy:history,holdingsStudy:{...meta,asOf:'',currency:'CNY',industrySystem:'',industryVersion:'',funds:[{id:'',allocation:null,currency:'CNY',reportDate:'',publishedAt:'',sourceUrl:'',locator:'',disclosureScope:'top10',equityWeight:null,holdings:[{market:'',code:'',shareClass:'ordinary',name:'',weight:null,industry:''}]}]},researchAudit:{...meta,asOf:'',timezone:'Asia/Shanghai',entities:[{id:'',market:'',code:'',name:'',shareClass:''}],observations:[{entityId:'',field:'',period:'',basis:'',unit:'',currency:'CNY',status:'notObtained',reason:''}],requestedCapabilities:[]},historical:history,correlationStudy:{...history,rollingObservations:60,minimumObservations:20,windows:[]},rebalance:{...history,capital:null,everyObservations:20,thresholdsPct:[3,5],costs:{commissionPct:null,minimumCommission:null,spreadBps:null,slippageBps:null},blockedDates:[]},shock:{...meta,capital:null,assumptions:[],assets:[{code:'',weight:null,shockPct:null}]},bondResearch:{...meta,priceType:'full',face:null,price:null,stockPrice:null,conversionPrice:null,yieldPct:null,cashflows:[{years:null,amount:null}],yieldScenarios:[]},financial:{...meta,period:'',periodEnd:'',publishedAt:'',asOf:'',currency:'CNY',unit:'',statementScope:'consolidated',periodBasis:'annual',sourceUrl:'',current:{assets:null,liabilities:null,equity:null,cash:null,restrictedCash:null,shortTermDebt:null,receivables:null,relatedReceivables:null},receivablesBasis:'gross',receivableAging:[]},convertibleTerms:{...meta,code:'',asOf:'',publishedAt:'',sourceUrl:'',clauses:[{kind:'downwardRevision',conditionText:'',locator:'',triggered:null,decision:'unknown',implemented:false}]}};
 if(kind==='bond')kind='bondResearch';if(!templates[kind])throw Error('未知模板类型');return clone(templates[kind]);
}
const api={inputTemplate,fundProfitStudy:d=>evaluate('fundProfitStudy',d),holdingsChange:d=>evaluate('holdingsChange',d),industryStudy:d=>evaluate('industryStudy',d),benchmarkStudy:d=>evaluate('benchmarkStudy',d),fundInvestorStudy:d=>evaluate('fundInvestorStudy',d),rollingRisk:d=>evaluate('rollingRisk',d),drawdownStudy:d=>evaluate('drawdownStudy',d),holdingsStudy:d=>evaluate('holdingsStudy',d),researchAudit:d=>evaluate('researchAudit',d),bondResearch:d=>evaluate('bondResearch',d),convertibleTerms:d=>evaluate('convertibleTerms',d),correlationStudy:d=>evaluate('correlationStudy',d),rebalance:d=>evaluate('rebalance',d),historical:d=>evaluate('historical',d),shock:d=>evaluate('shock',d),bond:d=>evaluate('bond',d),financial:d=>evaluate('financial',d),createSession,revise,invalidate,calculate};root.ResearchAnalytics=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);

